// Central Product type. Mirrors the `products` table in supabase/schema.sql.
//
// `specs` is intentionally a free-form JSON object (not fixed columns) so you
// can add/remove spec fields (material, voltage, weight, etc.) later without
// a database migration or code change — just add/remove keys in the admin
// form's JSON box.
export type ProductStatus = "active" | "inactive";

export interface Product {
  id: string; // uuid, generated by Supabase
  name: string; // product name / title
  description: string; // English long description
  price: number; // sale price, e.g. 39.99
  category: string; // e.g. "heated-belts" | "heated-socks" | "heated-gloves"
  specs: Record<string, string>; // free-form key/value spec sheet, e.g. { "Material": "...", "Voltage": "5V" }
  main_image: string | null; // public Supabase Storage URL
  gallery_images: string[]; // public Supabase Storage URLs, additional detail photos
  status: ProductStatus; // "active" shows on the storefront, "inactive" is off-shelf
  created_at: string;
  updated_at: string;
}

// Shape of the payload the admin form sends to create/update a product.
export type ProductInput = {
  name: string;
  description: string;
  price: number;
  category: string;
  specs: Record<string, string>;
  main_image: string | null;
  gallery_images: string[];
  status: ProductStatus;
};

// Categories shown in the storefront nav/filters. This is just a display list —
// `category` on a product is a free-text string, so you can introduce a new
// category any time by typing a new value in the admin form; add it here too
// so it shows up in the nav and filter dropdown.
export const CATEGORIES = [
  { id: "heated-belts", name: "Heated Belts" },
  { id: "heated-socks", name: "Heated Socks" },
  { id: "heated-gloves", name: "Heated Gloves" },
] as const;

// Editable static-content pages (About, Contact intro, Shipping, Return,
// Privacy). Mirrors the `pages` table in supabase/schema-pages.sql.
export interface SitePage {
  slug: string;
  title: string;
  content: string; // lightweight markdown — see PageContent component
  updated_at: string;
}

export const PAGE_SLUGS = [
  { slug: "about", label: "About Us" },
  { slug: "contact", label: "Contact Us (intro text only)" },
  { slug: "shipping", label: "Shipping Policy" },
  { slug: "return", label: "Return & Refund Policy" },
  { slug: "privacy", label: "Privacy Policy" },
] as const;

// Site-wide settings (currently just the homepage hero banner image).
// Mirrors the single row (id = 1) in the `site_settings` table in
// supabase/schema-settings.sql. hero_image is null until an admin
// uploads one from /admin/settings — the homepage falls back to the
// built-in /hero-1.svg in that case.
export interface SiteSettings {
  id: 1;
  hero_image: string | null;
  updated_at: string;
}
